name: Clan Snapshot
on: [workflow_dispatch]
permissions:
  contents: write
  actions: write
jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: nixervo/clan-snapshot-action{{ACTION_REF}}
        with:
          clan-id: {{CLAN_ID}}
